[package]
name = "common"
version = "0.0.1"

[features]
test-support = ["dep:git2"]

[dependencies]
serde_json = { workspace = true}
git2 = { workspace = true, optional = true }

rusqlite = { workspace = true }